[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[tool.setuptools_scm]

[project]
dynamic = ["version"]
name = "dkist-processing-cryonirsp"
requires-python = ">=3.11"
description = "Science processing code for the Cryo-NIRSP instrument on DKIST"
readme = "README.rst"
authors = [ {name = "NSO / AURA", email = "dkistdc@nso.edu"} ]
license = {text = "BSD-3-Clause"}
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "Pillow == 10.3.0",
  "astropy == 6.1.5",
  "dkist-fits-specifications == 4.11.0",
  "dkist-header-validator == 5.1.1",
  "dkist-processing-common == 10.5.12",
  "dkist-processing-math == 2.1.2",
  "dkist-processing-pac == 3.1.1",
  "dkist-spectral-lines == 3.0.0",
  "largestinteriorrectangle == 0.2.0",
  "dkist-service-configuration == 2.2",
  "moviepy == 2.0.0",
  "numba == 0.59.1",
  "numpy == 1.26.4",
  "peakutils == 1.3.5",
  "scikit-image == 0.23.2",
  "scipy == 1.15.1",
  "sunpy == 5.1.3",
]

[project.urls]
Homepage = "https://nso.edu/dkist/data-center/"
Repository = "https://bitbucket.org/dkistdc/dkist-processing-cryonirsp/"
Documentation = "https://docs.dkist.nso.edu/projects/cryo-nirsp"
Help = "https://nso.atlassian.net/servicedesk/customer/portal/5"

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
  "pytest-xdist",
  "pytest-mock",
  "hypothesis",
  "towncrier",
  "dkist-data-simulator >= 5.2.3",
  "dkist-processing-cryonirsp[inventory]",
  "dkist-processing-cryonirsp[asdf]",
  "dkist-processing-cryonirsp[quality]",
]
inventory = [
  "dkist-processing-common[inventory]",
  "dkist-inventory==1.6.1",
]
asdf = [
  "dkist-processing-common[asdf]",
  "dkist-inventory[asdf]==1.6.1",
]
quality = [
  "dkist-quality==1.2.1",
]
grogu = [
  "dkist",
  "pyparsing",
  "dkist-inventory >= 1.6.0",
]
docs = [
  "sphinx",
  "sphinx-astropy",
  "sphinx-changelog",
  "sphinx-autoapi == 3.3.3",
  "pytest",
  "towncrier",
  "dkist-sphinx-theme",
]

[tool.pytest.ini_options]
markers = [
  "development: For tests that can only be run while developing with a sidecar proxy (as opposed to in bitbucket pipelines)"
]

[tool.coverage.run]
omit = [
    "dkist_processing_cryonirsp/tests/*",
    "dkist_processing_cryonirsp/__init__.py",
]

[tool.coverage.report]
show_missing = true

[tool.towncrier]
    package = "dkist_processing_cryonirsp"
    filename = "CHANGELOG.rst"
    directory = "changelog/"
    issue_format = "`#{issue} <https://bitbucket.org/dkistdc/dkist-processing-cryonirsp/pull-requests/{issue}>`__"
    title_format = "{version} ({project_date})"
    ignore = [".gitempty", "*.science.rst"]

[[tool.towncrier.type]]
      directory = "feature"
      name = "Features"
      showcontent = true

[[tool.towncrier.type]]
      directory = "bugfix"
      name = "Bugfixes"
      showcontent = true

[[tool.towncrier.type]]
      directory = "removal"
      name = "Removals"
      showcontent = true

[[tool.towncrier.type]]
      directory = "misc"
      name = "Misc"
      showcontent = true

[[tool.towncrier.type]]
      directory = "doc"
      name = "Documentation"
      showcontent = true
