[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "at-common-schemas"
version = "1.0.2"
description = "Common schemas used by Apex Trader"
requires-python = ">=3.11"
authors = [
    {name = "Rui Chen"}
]
dependencies = [
    
]
readme = "README.md"

[project.urls]
"Homepage" = "https://github.com/apex-trader/at-common-schemas"
"Bug Tracker" = "https://github.com/apex-trader/at-common-schemas/issues"

[tool.setuptools]
packages = [
    "at_common_schemas",
    "at_common_schemas.service",
    "at_common_schemas.service.data",
    "at_common_schemas.service.data.calendar",
    "at_common_schemas.service.data.stock",
    "at_common_schemas.service.data.stock.financial",
    "at_common_schemas.service.data.news",
]

[tool.setuptools.package-data]
"at_common_schemas" = ["py.typed"]